name: Build Linux Qt Imageformat Plugins

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-plugins:  
    name: Build Image Plugins
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      options: --privileged
      volumes:
        - ${{ github.workspace }}:/reporoot
      
    steps:
      - uses: actions/checkout@v6
      - run: bash /reporoot/.github/workflows/build_qtplugins.sh

      - name: Upload Artifact
        if: contains(github.event.head_commit.message, '[deploy]') || startswith( github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7
        with:
          name: qt6.10.2imageformats
          path: /reporoot/build/lib/libq*.so
          retention-days: 7
